# if you want to try the docker as your development env:
# Prerequisite if you want to run TF or CLI:
#     export IBMCLOUD_API_KEY=<YOURS>
# Run:
#   docker-compose run tfworkspace
version: "3.3"
services:
  bootstrap-microservices:
    privileged: true
    build:
      context: .
    image: ghcr.io/ibm-xaas/dev-env:latest
    volumes:
      # For future ssh use in development
      - ~/.ssh:/home/ubuntu/.ssh:ro
      - .:/bootstrap-microservices/chapter-3
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      IBMCLOUD_API_KEY: "$IBMCLOUD_API_KEY"
    working_dir: /bootstrap-microservices/chapter-3
